yarnPath: ".yarn/releases/yarn-berry.cjs"

nodeLinker: node-modules

enableGlobalCache: true # move zip files from cacheFolder to global folder like $HOME/
# cacheFolder: "./.yarn/cache"
compressionLevel: 0
